language: java
sudo: false
jdk:
- openjdk8
#script:
#- mvn test
script: "mvn test   cobertura:cobertura"
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - '$HOME/.m2/repository'
